### ISSUE TITLE
result_cls wrapper for Context.evaluate()

### ISSUE THREAD

**Issue by mpounsett** [mpounsett/nagiosplugin#6]
**[Original report](https://bitbucket.org/flyingcircus/nagiosplugin/issue/6) by Christian Kauhaus (Bitbucket: [ckauhaus](https://bitbucket.org/ckauhaus), GitHub: [ckauhaus](https://github.com/ckauhaus)).**

----------------------------------------

I want to return just a state singleton from evaluate(). This avoid hard-to-debug errors like this:

```
#!python
CEPH UNKNOWN: AttributeError: 'Ok' object has no attribute 'state'
Traceback (most recent call last):
  File "/home/ckauhaus/.local/lib64/python3.2/site-packages/nagiosplugin/runtime.py", line 38, in wrapper
    return func(*args, **kwds)
  File "puppet/modules/sys_cluster/files/check_ceph_health.py", line 135, in main
    check.main(args.verbose, args.timeout)
[...]
  File "/home/ckauhaus/.local/lib64/python3.2/site-packages/nagiosplugin/check.py", line 81, in _evaluate_resource
    self.results.add(metric.evaluate())
  File "/home/ckauhaus/.local/lib64/python3.2/site-packages/nagiosplugin/result.py", line 116, in add
    self.by_state[result.state].append(result)
AttributeError: 'Ok' object has no attribute 'state'
```

Currently, evaluate() must return a Result object. Change base class to wrap Status singletons automatically using the result result class.

**Comment by mpounsett** [comment]
**Original comment by Christian Kauhaus (Bitbucket: [ckauhaus](https://bitbucket.org/ckauhaus), GitHub: [ckauhaus](https://github.com/ckauhaus)).**

----------------------------------------

Auto-wrap ServiceState object returned from Context.evaluate()

Usually evaluate() returns a Result object. In case no special features of
Result are needed, it is now ok for evalute() to return a bare ServiceState
object, which gets automatically wrapped into a Result.

Fixes #6
